name: Deploy Laravel to EC2

on:
  push:
    branches:
      - main  # Trigger the deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs the job on the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checkout the code from the repository

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh  # Create SSH directory
        echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa  # Add the EC2 private key
        chmod 600 ~/.ssh/id_rsa  # Set the correct permissions for the private key
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts  # Add the EC2 host to known hosts to prevent SSH warnings

        - name: Deploy to EC2
      run: |
        ssh -v ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          echo "Navigating to project directory"
          cd ${{ secrets.PROJECT_PATH }} || exit

          echo "Pulling the latest code"
          git pull origin main || exit

          echo "Installing Composer dependencies"
          composer install --no-interaction --prefer-dist --optimize-autoloader || exit

          echo "Running fresh migrations"
          php artisan migrate:fresh --force || exit  # DANGER: Drops all tables and recreates them

          echo "Caching configuration, routes, and views"
          php artisan config:cache || exit
          php artisan route:cache || exit
          php artisan view:cache || exit

          echo "Restarting Nginx"
          sudo systemctl restart nginx || exit
        EOF

